import { isIntegerPaise, isIsoDate } from "../database/validation.js";

const DAY = 86400000; const addDays = (date, days) => new Date(Date.parse(`${date}T00:00:00Z`) + days * DAY).toISOString().slice(0, 10);
export function buildForecast({ asOfDate, days, openingBalancePaise, occurrences = [], minimumReservePaise = 0, includeUncertain = false }) {
  if (!isIsoDate(asOfDate) || !Number.isInteger(days) || days < 1 || !Number.isSafeInteger(openingBalancePaise) || !isIntegerPaise(minimumReservePaise)) throw new TypeError("Forecast inputs are invalid.");
  const throughDate = addDays(asOfDate, days); const eligible = occurrences.filter((item) => item.dueDate > asOfDate && item.dueDate <= throughDate && !["skipped", "paid", "received", "auto-posted"].includes(item.status) && (includeUncertain || !item.uncertain)); let balancePaise = openingBalancePaise; const timeline = []; const shortfallCauses = [];
  for (const item of [...eligible].sort((a, b) => a.dueDate.localeCompare(b.dueDate))) { const amount = item.actualAmountPaise ?? item.expectedAmountPaise; const deltaPaise = item.kind === "income" ? amount : -amount; balancePaise += deltaPaise; const confidence = item.actualAmountPaise != null || item.estimateType === "fixed" ? "confirmed" : "estimated"; const event = { occurrenceId: item.id, name: item.name, date: item.dueDate, deltaPaise, balancePaise, confidence, uncertain: Boolean(item.uncertain) }; timeline.push(event); if (balancePaise < minimumReservePaise) shortfallCauses.push({ ...event, shortfallPaise: minimumReservePaise - balancePaise }); }
  const commitmentsPaise = eligible.filter((item) => item.kind === "commitment").reduce((sum, item) => sum + (item.actualAmountPaise ?? item.expectedAmountPaise), 0); const confirmedIncomePaise = eligible.filter((item) => item.kind === "income" && (item.actualAmountPaise != null || item.estimateType === "fixed")).reduce((sum, item) => sum + (item.actualAmountPaise ?? item.expectedAmountPaise), 0);
  const safeToSpendPaise = Math.max(0, openingBalancePaise + confirmedIncomePaise - commitmentsPaise - minimumReservePaise);
  return { asOfDate, throughDate, days, openingBalancePaise, projectedBalancePaise: balancePaise, minimumReservePaise, safeToSpendPaise, expectedInvestmentSurplusPaise: safeToSpendPaise, timeline, shortfallCauses, assumptions: { includeUncertain, occurrenceCount: eligible.length, transfersExcluded: true, minimumReservePaise, incomePolicy: "Only fixed or actual income increases safe-to-spend; all included commitments reduce it." } };
}

export function goalProgress(goal, asOfDate) { if (!isIntegerPaise(goal.targetAmountPaise) || !isIntegerPaise(goal.currentAmountPaise ?? 0) || !isIsoDate(goal.targetDate) || !isIsoDate(asOfDate)) throw new TypeError("Goal inputs are invalid."); const gapPaise = Math.max(0, goal.targetAmountPaise - (goal.currentAmountPaise ?? 0)); const start = new Date(`${asOfDate}T00:00:00Z`); const target = new Date(`${goal.targetDate}T00:00:00Z`); const months = Math.max(1, (target.getUTCFullYear() - start.getUTCFullYear()) * 12 + target.getUTCMonth() - start.getUTCMonth()); return { goalId: goal.id, targetAmountPaise: goal.targetAmountPaise, currentAmountPaise: goal.currentAmountPaise ?? 0, gapPaise, targetDate: goal.targetDate, monthsRemaining: months, requiredMonthlyContributionPaise: Math.ceil(gapPaise / months), status: gapPaise === 0 ? "achieved" : goal.targetDate < asOfDate ? "overdue" : "in-progress" }; }
