const csvCell = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export function buildReportDataset({ transactions = [], effects = [], categories = [], accounts = [], familyMembers = [], filters = {}, generatedAt = new Date().toISOString(), investmentPriceTimestamp = null }) {
  const txById = new Map(transactions.map((tx) => [tx.id, tx])); const categoryById = new Map(categories.map((item) => [item.id, item])); const accountById = new Map(accounts.map((item) => [item.id, item])); const familyById = new Map(familyMembers.map((item) => [item.id, item]));
  const merchantQuery = String(filters.merchant ?? "").trim().toLocaleLowerCase();
  const selected = transactions.filter((tx) => tx.status === "posted" && (!filters.dateFrom || tx.accountingDate >= filters.dateFrom) && (!filters.dateTo || tx.accountingDate <= filters.dateTo) && (!filters.accountId || tx.sourceAccountId === filters.accountId || tx.destinationAccountId === filters.accountId) && (!filters.categoryId || tx.categoryId === filters.categoryId) && (!merchantQuery || String(tx.merchantText ?? "").toLocaleLowerCase().includes(merchantQuery))); const ids = new Set(selected.map((tx) => tx.id));
  const rows = selected.sort((a, b) => a.accountingDate.localeCompare(b.accountingDate)).map((tx) => ({ id: tx.id, date: tx.accountingDate, type: tx.type, amountPaise: tx.amountPaise, account: accountById.get(tx.sourceAccountId ?? tx.destinationAccountId)?.nickname ?? "", category: categoryById.get(tx.categoryId)?.name ?? "Uncategorised", familyMember: familyById.get(tx.familyMemberId)?.name ?? "", merchant: tx.merchantText ?? "", notes: filters.includeNotes ? tx.notes ?? "" : "", receiptCount: filters.includeReceipts ? tx.receiptIds?.length ?? 0 : 0 }));
  const relevantEffects = effects.filter((effect) => ids.has(effect.transactionId) && effect.active); const incomePaise = relevantEffects.filter((e) => e.dimension === "income").reduce((s, e) => s + e.amountPaise, 0); const expensePaise = relevantEffects.filter((e) => e.dimension === "expense").reduce((s, e) => s + e.amountPaise, 0);
  const expenseFor = (predicate) => relevantEffects.filter((effect) => effect.dimension === "expense" && predicate(txById.get(effect.transactionId))).reduce((sum, effect) => sum + effect.amountPaise, 0);
  const byCategory = [...new Set(rows.map(({ category }) => category))].map((category) => ({ category, amountPaise: expenseFor((tx) => tx && (categoryById.get(tx.categoryId)?.name ?? "Uncategorised") === category) })).sort((a, b) => b.amountPaise - a.amountPaise);
  const byMerchant = [...new Set(rows.map(({ merchant }) => merchant || "Unspecified"))].map((merchant) => ({ merchant, amountPaise: expenseFor((tx) => tx && (tx.merchantText || "Unspecified") === merchant) })).sort((a, b) => b.amountPaise - a.amountPaise);
  return { generatedAt, investmentPriceTimestamp, filters: { ...filters, includeReceipts: Boolean(filters.includeReceipts), includeNotes: Boolean(filters.includeNotes), maskIdentifiers: filters.maskIdentifiers !== false }, rows, totals: { incomePaise, expensePaise, savingsPaise: incomePaise - expensePaise, transactionAmountPaise: rows.reduce((sum, row) => sum + row.amountPaise, 0) }, byCategory, byMerchant };
}
export function reportPeriod(preset, anchor = new Date().toISOString().slice(0, 10)) { const date = new Date(`${anchor}T00:00:00Z`); const year = date.getUTCFullYear(); const month = date.getUTCMonth(); const iso = (value) => value.toISOString().slice(0, 10); if (preset === "monthly") return { dateFrom: `${year}-${String(month + 1).padStart(2, "0")}-01`, dateTo: iso(new Date(Date.UTC(year, month + 1, 0))) }; if (preset === "quarterly") { const start = Math.floor(month / 3) * 3; return { dateFrom: `${year}-${String(start + 1).padStart(2, "0")}-01`, dateTo: iso(new Date(Date.UTC(year, start + 3, 0))) }; } if (preset === "yearly") return { dateFrom: `${year}-01-01`, dateTo: `${year}-12-31` }; if (preset === "financial-year") { const start = month >= 3 ? year : year - 1; return { dateFrom: `${start}-04-01`, dateTo: `${start + 1}-03-31` }; } return {};
}
export function reportToCsv(report) { const columns = ["Date", "Type", "AmountPaise", "Account", "Category", "FamilyMember", "Merchant", ...(report.filters.includeNotes ? ["Notes"] : [])]; const lines = [columns.map(csvCell).join(",")]; for (const row of report.rows) lines.push([row.date, row.type, row.amountPaise, row.account, row.category, row.familyMember, row.merchant, ...(report.filters.includeNotes ? [row.notes] : [])].map(csvCell).join(",")); return `${lines.join("\r\n")}\r\n`; }
