import { RECURRENCE_FREQUENCIES, validateRecurringRule } from "../../engines/recurrence-engine.js";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const element = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };
const dateShift = (date, days) => new Date(new Date(`${date}T00:00:00Z`).getTime() + days * 86400000).toISOString().slice(0, 10);
const rupeesToPaise = (value) => { const match = String(value).trim().match(/^(\d+)(?:\.(\d{1,2}))?$/); return match ? Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0")) : null; };
function field(label, control) { const wrapper = element("label", null, "field"); wrapper.append(element("span", label), control); return wrapper; }
function input(type, name, value = "") { const control = element("input"); control.type = type; control.name = name; control.value = value; return control; }

export function createRecurringCenter({ recurring, entities, transactions, liveRegion }) {
  const root = element("section", null, "recurring-center"); let generation = 0;
  function ruleEditor(today, accounts) {
    const details = element("details", null, "recurring-editor"); details.append(element("summary", "Add recurring income or commitment")); const form = element("form", null, "recurring-editor__form");
    const kind = element("select"); kind.name = "kind"; kind.append(new Option("Income", "incomeSource"), new Option("Commitment", "commitment"));
    const frequency = element("select"); frequency.name = "frequency"; for (const item of RECURRENCE_FREQUENCIES) frequency.append(new Option(item.replaceAll("-", " "), item));
    const estimate = element("select"); estimate.name = "estimateType"; estimate.append(new Option("Fixed amount", "fixed"), new Option("Variable estimate", "variable")); const account = element("select"); account.name = "accountId"; account.append(new Option("No linked account", ""), ...accounts.map((item) => new Option(item.nickname, item.id))); const autoPost = input("checkbox", "autoPost"); const submit = element("button", "Save recurring rule", "button"); submit.type = "submit";
    form.append(field("Type", kind), field("Name", input("text", "name")), field("Expected amount (rupees)", input("text", "amount")), field("Frequency", frequency), field("Amount behavior", estimate), field("Posting account (optional)", account), field("Auto-post when due", autoPost), field("Start date", input("date", "startDate", today)), field("End date (optional)", input("date", "endDate")), field("Day of month (optional)", input("number", "dayOfMonth")), field("Custom interval days", input("number", "intervalDays")), field("Specific dates, comma separated", input("text", "specificDates")), submit);
    form.onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const amount = rupeesToPaise(data.amount); if (amount == null) { liveRegion.textContent = "Enter a valid non-negative amount."; return; } const isIncome = data.kind === "incomeSource"; const record = { name: data.name.trim(), [isIncome ? "incomeType" : "commitmentType"]: "custom", [isIncome ? "destinationAccountId" : "sourceAccountId"]: data.accountId || undefined, expectedAmountPaise: amount, frequency: data.frequency, estimateType: data.estimateType, startDate: data.startDate, endDate: data.endDate || undefined, dayOfMonth: data.dayOfMonth ? Number(data.dayOfMonth) : undefined, intervalDays: data.intervalDays ? Number(data.intervalDays) : undefined, specificDates: data.specificDates ? data.specificDates.split(",").map((date) => date.trim()).filter(Boolean) : undefined, status: "active", autoPost: data.autoPost === "on" }; if (record.autoPost && (!data.accountId || record.estimateType === "variable")) { liveRegion.textContent = "Auto-posting requires a linked account and a fixed amount."; return; } const recurrenceErrors = validateRecurringRule({ ...record, id: "pending_rule" }); if (Object.keys(recurrenceErrors).length) { liveRegion.textContent = Object.values(recurrenceErrors)[0]; return; } submit.disabled = true; const result = await entities.save(data.kind, record); if (!result.ok) { liveRegion.textContent = Object.values(result.errors)[0]; submit.disabled = false; return; } liveRegion.textContent = "Recurring rule saved. Its due occurrences are now available for review."; await render(); };
    details.append(form); return details;
  }
  async function act(item, action) {
    try { const detail = {}; if (action === "confirm" && item.estimateType === "variable") { const value = prompt("Actual amount in rupees", (item.expectedAmountPaise / 100).toFixed(2)); if (value == null) return; detail.actualAmountPaise = rupeesToPaise(value); } if (action === "postpone") { const dueDate = prompt("New due date (YYYY-MM-DD)", dateShift(item.dueDate, 1)); if (!dueDate) return; detail.dueDate = dueDate; } if (action === "skip") detail.reason = prompt("Reason for skipping (optional)") ?? ""; if (action === "confirm") await recurring.confirmAndPost(item.id, detail); else await recurring.transition(item.id, action, detail); liveRegion.textContent = `Recurring item ${action === "confirm" ? "confirmed" : `${action}d`}.`; await render(); } catch (error) { liveRegion.textContent = error.cause?.message ?? error.message; }
  }
  async function render() {
    const current = ++generation; const today = new Date().toISOString().slice(0, 10); await recurring.generate(dateShift(today, -35), dateShift(today, 100), { today }); const [items, rules, accounts] = await Promise.all([recurring.list({ fromDate: dateShift(today, -35), toDate: dateShift(today, 100), today }), recurring.listRules(), entities.list("account", { status: "active" })]); if (current !== generation) return;
    const open = items.filter(({ status }) => !["paid", "received", "skipped", "auto-posted"].includes(status)); const overdue = open.filter(({ status }) => status === "overdue"); const header = element("header", null, "recurring-center__header"); header.append(element("p", "Make tomorrow visible", "route-heading__eyebrow"), element("h1", "Recurring plan"), element("p", `${open.length} open · ${overdue.length} overdue. Missed items remain visible until you confirm, skip, or postpone them.`)); if ("Notification" in window && Notification.permission !== "granted") { const enable = element("button", "Enable browser reminders", "button button--secondary"); enable.onclick = async () => { const permission = await Notification.requestPermission(); liveRegion.textContent = permission === "granted" ? "Browser reminders enabled." : "Browser reminders remain disabled."; if (permission === "granted") await render(); }; header.append(enable); } else if ("Notification" in window) await recurring.deliverDueReminders(({ occurrence }) => new Notification(`FinOrbit: ${occurrence.name}`, { body: `${money.format(occurrence.expectedAmountPaise / 100)} was due ${occurrence.dueDate}.`, tag: occurrence.id }));
    const totals = element("section", null, "transaction-summary"); const expectedIncome = open.filter(({ kind }) => kind === "income").reduce((sum, item) => sum + item.expectedAmountPaise, 0); const expectedCommitments = open.filter(({ kind }) => kind === "commitment").reduce((sum, item) => sum + item.expectedAmountPaise, 0); totals.append(element("h2", "Expected in this window"), element("p", `${money.format(expectedIncome / 100)} income · ${money.format(expectedCommitments / 100)} commitments`));
    const warnings = element("section", null, "transaction-summary"); warnings.append(element("h2", "Balance warnings")); const shortfalls = []; for (const account of accounts) { const commitments = open.filter((item) => item.sourceAccountId === account.id && item.dueDate <= dateShift(today, 30)).reduce((sum, item) => sum + item.expectedAmountPaise, 0); if (commitments && await transactions.project("account", account.id) < commitments) shortfalls.push(`${account.nickname} may not cover ${money.format(commitments / 100)} due within 30 days.`); } warnings.append(element("p", shortfalls.length ? shortfalls.join(" ") : "No linked-account shortfalls detected for the next 30 days."));
    const ruleList = element("section", null, "transaction-summary"); ruleList.append(element("h2", "Recurring rules")); for (const rule of rules) { const row = element("div", null, "recurring-rule"); row.append(element("span", `${rule.name} · ${rule.frequency.replaceAll("-", " ")} · ${rule.status}${rule.autoPost ? " · auto-post" : ""}`)); const toggle = element("button", rule.status === "active" ? "Pause" : "Resume", "button button--secondary"); toggle.onclick = async () => { await recurring.setRuleStatus(rule.id, rule.status === "active" ? "inactive" : "active"); liveRegion.textContent = `${rule.name} ${rule.status === "active" ? "paused" : "resumed"}.`; await render(); }; row.append(toggle); ruleList.append(row); } if (!rules.length) ruleList.append(element("p", "No recurring rules yet."));
    const list = element("ol", null, "recurring-list"); for (const item of items) { const row = element("li", null, `recurring-list__item status-${item.status}`); const info = element("div"); info.append(element("strong", item.name), element("span", ` ${item.dueDate} · ${money.format(item.expectedAmountPaise / 100)} · ${item.status.replaceAll("-", " ")}${item.actualAmountPaise != null ? ` · actual ${money.format(item.actualAmountPaise / 100)}` : ""}`)); row.append(info); if (open.includes(item)) { const actions = element("div", null, "recurring-list__actions"); for (const [action, label] of [["confirm", item.kind === "income" ? "Received" : "Paid"], ["postpone", "Postpone"], ["skip", "Skip"]]) { const button = element("button", label, `button ${action === "confirm" ? "" : "button--secondary"}`); button.onclick = () => act(item, action); actions.append(button); } row.append(actions); } list.append(row); } if (!items.length) list.append(element("li", "No occurrences in this date window. Add an active recurring rule to begin.")); root.replaceChildren(header, totals, warnings, ruleEditor(today, accounts), ruleList, list);
  }
  return { element: root, start: render };
}
