import { createAuditEvent } from "../database/audit.js";
import { runTransaction } from "../database/transaction.js";
import { createOpaqueId, isIntegerPaise } from "../database/validation.js";
import { calculateBudgets, priorBudgetMonth, validateBudget } from "../engines/budget-engine.js";

const CLASSIFICATIONS = new Set(["essential", "discretionary", "financial-commitment", "wealth-building", "income"]);
const cleanName = (value) => String(value ?? "").trim();

export function createHouseholdService(database, { now = () => new Date().toISOString(), id = () => createOpaqueId() } = {}) {
  async function saveCategory(input) {
    const name = cleanName(input.name); if (!name) return { ok: false, errors: { name: "Enter a category name." } };
    if (!CLASSIFICATIONS.has(input.classification)) return { ok: false, errors: { classification: "Choose a supported classification." } };
    const nameKey = name.toLocaleLowerCase("en-IN"); const records = await runTransaction(database, ["categories"], "readonly", ({ store }) => store("categories").getAll());
    if (records.some((item) => item.id !== input.id && item.nameKey === nameKey)) return { ok: false, errors: { name: "A category with this name already exists." } };
    const instant = now(); const prior = input.id ? records.find(({ id }) => id === input.id) : null; const record = { ...input, id: input.id ?? id(), name, nameKey, icon: input.icon || "tag", hidden: Boolean(input.hidden), archived: Boolean(input.archived), status: "active", createdAt: prior?.createdAt ?? instant, updatedAt: instant, schemaVersion: 5 };
    await runTransaction(database, ["categories", "auditLogs"], "readwrite", async ({ store }) => { await store("categories").put(record); await store("auditLogs").add(createAuditEvent(prior ? "entity.edited" : "entity.created", { entityType: "category", entityId: record.id })); }); return { ok: true, record };
  }
  async function setCategoryHidden(categoryId, hidden) { return runTransaction(database, ["categories", "auditLogs"], "readwrite", async ({ store }) => { const record = await store("categories").get(categoryId); if (!record) throw new Error("Category not found."); record.hidden = Boolean(hidden); record.updatedAt = now(); await store("categories").put(record); await store("auditLogs").add(createAuditEvent("category.hidden", { categoryId, hidden: record.hidden })); return record; }); }
  async function listCategories({ includeHidden = false } = {}) { return (await runTransaction(database, ["categories"], "readonly", ({ store }) => store("categories").getAll())).filter((item) => !item.archived && (includeHidden || !item.hidden)).sort((a, b) => a.name.localeCompare(b.name)); }
  async function saveSubcategory(input) { const name = cleanName(input.name); const parent = input.categoryId && await runTransaction(database, ["categories"], "readonly", ({ store }) => store("categories").get(input.categoryId)); if (!name || !parent) return { ok: false, errors: { [!name ? "name" : "categoryId"]: !name ? "Enter a subcategory name." : "Choose an existing category." } }; const instant = now(); const record = { ...input, id: input.id ?? id(), name, nameKey: name.toLocaleLowerCase("en-IN"), archived: false, createdAt: input.createdAt ?? instant, updatedAt: instant, schemaVersion: 5 }; await runTransaction(database, ["subcategories", "auditLogs"], "readwrite", async ({ store }) => { await store("subcategories").put(record); await store("auditLogs").add(createAuditEvent(input.id ? "entity.edited" : "entity.created", { entityType: "subcategory", entityId: record.id })); }); return { ok: true, record }; }
  async function saveFamilyMember(input) { const name = cleanName(input.name); if (!name) return { ok: false, errors: { name: "Enter a family member name." } }; const instant = now(); const record = { ...input, id: input.id ?? id(), name, nameKey: name.toLocaleLowerCase("en-IN"), status: "active", archived: false, createdAt: input.createdAt ?? instant, updatedAt: instant, schemaVersion: 5 }; await runTransaction(database, ["familyMembers", "auditLogs"], "readwrite", async ({ store }) => { await store("familyMembers").put(record); await store("auditLogs").add(createAuditEvent(input.id ? "entity.edited" : "entity.created", { entityType: "familyMember", entityId: record.id })); }); return { ok: true, record }; }
  async function saveBudget(input) { const record = { ...input, id: input.id ?? `budget_${input.categoryId}_${String(input.month).replace("-", "")}`, rolloverMode: input.rolloverMode ?? "none", archived: false }; const errors = validateBudget(record); if (Object.keys(errors).length) return { ok: false, errors }; const category = await runTransaction(database, ["categories"], "readonly", ({ store }) => store("categories").get(record.categoryId)); if (!category) return { ok: false, errors: { categoryId: "Choose an existing category." } }; const instant = now(); const prior = await runTransaction(database, ["budgets"], "readonly", ({ store }) => store("budgets").get(record.id)); Object.assign(record, { createdAt: prior?.createdAt ?? instant, updatedAt: instant, schemaVersion: 5 }); await runTransaction(database, ["budgets", "auditLogs"], "readwrite", async ({ store }) => { await store("budgets").put(record); await store("auditLogs").add(createAuditEvent("budget.saved", { budgetId: record.id, categoryId: record.categoryId, month: record.month })); }); return { ok: true, record }; }
  async function calculate(month, asOfDate = `${month}-${new Date(Date.UTC(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0)).getUTCDate()}`) {
    const [budgets, transactions, effects] = await runTransaction(database, ["budgets", "transactions", "transactionEffects"], "readonly", async ({ store }) => Promise.all([store("budgets").getAll(), store("transactions").getAll(), store("transactionEffects").getAll()]));
    const previous = priorBudgetMonth(month); const previousResults = calculateBudgets({ budgets, transactions, effects, month: previous }); return calculateBudgets({ budgets, transactions, effects, month, asOfDate, previousResults });
  }
  async function listFamilyMembers() { return (await runTransaction(database, ["familyMembers"], "readonly", ({ store }) => store("familyMembers").getAll())).filter((item) => !item.archived).sort((a, b) => a.name.localeCompare(b.name)); }
  return { saveCategory, setCategoryHidden, listCategories, saveSubcategory, saveFamilyMember, listFamilyMembers, saveBudget, calculate };
}
