import { runTransaction } from "../database/transaction.js";
import { createAuditEvent } from "../database/audit.js";
import { createOpaqueId, isDecimalString, isIntegerPaise, isIsoDate } from "../database/validation.js";
import { calculatePortfolio } from "../engines/portfolio-engine.js";

export function createPortfolioService(database, { now = () => new Date().toISOString(), id = () => createOpaqueId() } = {}) {
  async function saveLot(input) { const errors = {}; if (!input.investmentId) errors.investmentId = "Choose an investment."; if (!isDecimalString(input.quantity) || input.quantity === "0") errors.quantity = "Enter a positive decimal quantity."; if (!isIntegerPaise(input.costBasisPaise)) errors.costBasisPaise = "Enter cost basis in whole paise."; if (!isIsoDate(input.purchaseDate)) errors.purchaseDate = "Enter a purchase date."; const investment = input.investmentId && await runTransaction(database, ["investments"], "readonly", ({ store }) => store("investments").get(input.investmentId)); if (!investment) errors.investmentId = "Choose an existing investment."; if (Object.keys(errors).length) return { ok: false, errors }; const instant = now(); const record = { ...input, id: input.id ?? id(), archived: false, createdAt: input.createdAt ?? instant, updatedAt: instant, schemaVersion: 6 }; await runTransaction(database, ["investmentLots", "auditLogs"], "readwrite", async ({ store }) => { await store("investmentLots").put(record); await store("auditLogs").add(createAuditEvent(input.id ? "entity.edited" : "entity.created", { entityType: "investmentLot", entityId: record.id, investmentId: record.investmentId })); }); return { ok: true, record }; }
  async function calculate() { const [investments, lots, valuations] = await runTransaction(database, ["investments", "investmentLots", "marketPrices"], "readonly", async ({ store }) => Promise.all([store("investments").getAll(), store("investmentLots").getAll(), store("marketPrices").getAll()])); return calculatePortfolio({ investments, lots, valuations }); }
  async function listInvestments() { return (await runTransaction(database, ["investments"], "readonly", ({ store }) => store("investments").getAll())).filter((item) => !item.archived && item.status === "active").sort((a, b) => a.name.localeCompare(b.name)); }
  async function listLots(investmentId) { return (await runTransaction(database, ["investmentLots"], "readonly", ({ store }) => store("investmentLots").indexGetAll("byInvestmentId", investmentId))).filter((item) => !item.archived).sort((a, b) => b.purchaseDate.localeCompare(a.purchaseDate)); }
  return { saveLot, calculate, listInvestments, listLots };
}
