import test from "node:test";
import assert from "node:assert/strict";
import { IDBFactory } from "fake-indexeddb";
import { openDatabase } from "../src/database/connection.js";
import { runTransaction } from "../src/database/transaction.js";
import { createHouseholdService } from "../src/services/household-service.js";

async function fixture() { const database = await openDatabase({ indexedDB: new IDBFactory(), name: crypto.randomUUID() }); let sequence = 0; return { database, service: createHouseholdService(database, { now: () => "2026-09-15T10:00:00.000Z", id: () => `household_${++sequence}` }) }; }

test("custom category can be hidden without breaking historical attribution", async () => { const { database, service } = await fixture(); const saved = await service.saveCategory({ name: "Pet care", classification: "essential", icon: "heart" }); assert.equal(saved.ok, true); await service.setCategoryHidden(saved.record.id, true); assert.equal((await service.listCategories()).length, 0); assert.equal((await service.listCategories({ includeHidden: true }))[0].hidden, true); database.close(); });
test("subcategories require stable parent categories", async () => { const { database, service } = await fixture(); assert.equal((await service.saveSubcategory({ name: "Dry food", categoryId: "missing" })).ok, false); const category = (await service.saveCategory({ name: "Pet care", classification: "essential" })).record; assert.equal((await service.saveSubcategory({ name: "Dry food", categoryId: category.id })).ok, true); database.close(); });
test("family members are durable transaction attribution targets", async () => { const { database, service } = await fixture(); const result = await service.saveFamilyMember({ name: "Asha", relationship: "parent" }); assert.equal(result.ok, true); assert.equal((await service.listFamilyMembers())[0].relationship, "parent"); database.close(); });
test("saved budgets reconcile exactly to classified transaction effects", async () => { const { database, service } = await fixture(); const category = (await service.saveCategory({ name: "School fees", classification: "financial-commitment" })).record; await service.saveBudget({ categoryId: category.id, month: "2026-09", limitPaise: 500000, rolloverMode: "none" }); await runTransaction(database, ["transactions", "transactionEffects"], "readwrite", async ({ store }) => { await store("transactions").add({ id: "transaction_school", type: "expense", status: "posted", accountingDate: "2026-09-10", categoryId: category.id }); await store("transactionEffects").add({ id: "effect_school", transactionId: "transaction_school", dimension: "expense", amountPaise: 200000, active: true }); }); const [result] = await service.calculate("2026-09", "2026-09-15"); assert.equal(result.spentPaise, 200000); assert.equal(result.remainingPaise, 300000); database.close(); });
