import test from "node:test";
import assert from "node:assert/strict";
import { IDBFactory } from "fake-indexeddb";
import { openDatabase } from "../src/database/connection.js";
import { runTransaction } from "../src/database/transaction.js";
import { createOnboardingService, ONBOARDING_STAGES } from "../src/services/onboarding-service.js";
import { createEntityService } from "../src/services/entity-service.js";

async function fixture() { const database = await openDatabase({ indexedDB: new IDBFactory(), name: crypto.randomUUID() }); return { database, onboarding: createOnboardingService(database), entities: createEntityService(database) }; }
test("fresh onboarding starts at welcome and exposes the simplified 11 stages", async () => { const { database, onboarding } = await fixture(); assert.equal((await onboarding.read()).stage, 0); assert.equal(ONBOARDING_STAGES.length, 11); assert.equal(ONBOARDING_STAGES.includes("properties"), false); assert.equal(ONBOARDING_STAGES.includes("vehicles"), false); database.close(); });
test("onboarding saves, resumes, moves backward and preserves validation drafts", async () => { const { database, onboarding } = await fixture(); await onboarding.saveProgress({ stage: 4, drafts: { profile: { displayName: "Sam" } } }); const state = await onboarding.read(); assert.equal(state.stage, 4); assert.equal(state.drafts.profile.displayName, "Sam"); await onboarding.saveProgress({ stage: 3, drafts: state.drafts }); assert.equal((await onboarding.read()).stage, 3); database.close(); });
test("profile uses INR/en-IN without unnecessary identity fields", async () => { const { database, onboarding } = await fixture(); const result = await onboarding.saveProfile({ displayName: "Sam", currency: "INR", locale: "en-IN", financialYearStartMonth: 4, dateFormat: "DD/MM/YYYY" }); assert.equal(result.ok, true); assert.equal(result.profile.pan, undefined); assert.equal(result.profile.aadhaar, undefined); database.close(); });
test("completion requires a profile and one active usable money source", async () => { const { database, onboarding, entities } = await fixture(); await assert.rejects(onboarding.complete(), /profile/); await onboarding.saveProfile({ displayName: "Sam", currency: "INR", financialYearStartMonth: 4, dateFormat: "DD/MM/YYYY" }); await assert.rejects(onboarding.complete(), /active money source/); await entities.save("account", { nickname: "Cash", accountType: "cash", openingBalancePaise: 0, includeInNetWorth: true, status: "active" }); const profile = await onboarding.complete(); assert.equal(profile.setupCompleted, true); assert.equal((await onboarding.read()).completed, true); database.close(); });
test("security settings remain untouched throughout onboarding", async () => { const { database, onboarding } = await fixture(); await runTransaction(database, ["settings"], "readwrite", ({ store }) => store("settings").put({ id: "security.credential", mode: "PIN", updatedAt: new Date().toISOString() })); await onboarding.saveProgress({ stage: 2, drafts: {} }); assert.equal((await runTransaction(database, ["settings"], "readonly", ({ store }) => store("settings").get("security.credential"))).mode, "PIN"); database.close(); });
test("legacy property and vehicle setup stages resume at emergency fund without data loss", async () => { const { database, onboarding } = await fixture(); await runTransaction(database, ["settings"], "readwrite", ({ store }) => store("settings").put({ id: "onboarding.progress", stage: 9, drafts: { vehicles: { nickname: "Bike 1" } }, completed: false, schemaVersion: 2 })); const state = await onboarding.read(); assert.equal(state.stage, 8); assert.equal(state.drafts.vehicles.nickname, "Bike 1"); database.close(); });
