const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const element = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };
const field = (label, control) => { const wrapper = element("label", null, "field"); wrapper.append(element("span", label), control); return wrapper; };
const input = (name, type = "text") => { const control = element("input"); control.name = name; control.type = type; return control; };
const paise = (value) => { const match = String(value).trim().match(/^(\d+)(?:\.(\d{1,2}))?$/); return match ? Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0")) : null; };

export function createHouseholdCenter({ household, liveRegion }) {
  const root = element("section", null, "household-center"); let selectedMonth = new Date().toISOString().slice(0, 7); let generation = 0;
  function categoryForm() { const form = element("form", null, "household-form"); const classification = element("select"); classification.name = "classification"; for (const value of ["essential", "discretionary", "financial-commitment", "wealth-building"]) classification.append(new Option(value.replaceAll("-", " "), value)); const save = element("button", "Add category", "button"); save.type = "submit"; form.append(field("Custom category", input("name")), field("Classification", classification), field("Icon label", input("icon")), save); form.onsubmit = async (event) => { event.preventDefault(); const result = await household.saveCategory(Object.fromEntries(new FormData(form))); liveRegion.textContent = result.ok ? "Category added." : Object.values(result.errors)[0]; if (result.ok) await render(); }; return form; }
  function familyForm() { const form = element("form", null, "household-form"); const save = element("button", "Add family member", "button"); save.type = "submit"; form.append(field("Family member", input("name")), field("Relationship", input("relationship")), save); form.onsubmit = async (event) => { event.preventDefault(); const result = await household.saveFamilyMember(Object.fromEntries(new FormData(form))); liveRegion.textContent = result.ok ? "Family member added for transaction attribution." : Object.values(result.errors)[0]; if (result.ok) await render(); }; return form; }
  function subcategoryForm(categories) { const form = element("form", null, "household-form"); const category = element("select"); category.name = "categoryId"; for (const item of categories) category.append(new Option(item.name, item.id)); const save = element("button", "Add subcategory", "button"); save.type = "submit"; form.append(field("Parent category", category), field("Subcategory", input("name")), save); form.onsubmit = async (event) => { event.preventDefault(); const result = await household.saveSubcategory(Object.fromEntries(new FormData(form))); liveRegion.textContent = result.ok ? "Subcategory added." : Object.values(result.errors)[0]; }; return form; }
  function budgetForm(categories) { const form = element("form", null, "household-form"); const category = element("select"); category.name = "categoryId"; for (const item of categories.filter(({ classification }) => classification !== "income")) category.append(new Option(item.name, item.id)); const month = input("month", "month"); month.value = selectedMonth; const rollover = element("select"); rollover.name = "rolloverMode"; rollover.append(new Option("No rollover", "none"), new Option("Carry unused amount", "positive-only"), new Option("Carry surplus or overspend", "full")); const save = element("button", "Save budget", "button"); save.type = "submit"; form.append(field("Category", category), field("Month", month), field("Limit (rupees)", input("limit")), field("Rollover", rollover), save); form.onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const limitPaise = paise(data.limit); if (limitPaise == null) { liveRegion.textContent = "Enter a valid budget amount."; return; } const result = await household.saveBudget({ ...data, limitPaise }); liveRegion.textContent = result.ok ? "Monthly budget saved." : Object.values(result.errors)[0]; if (result.ok) { selectedMonth = data.month; await render(); } }; return form; }
  async function render() { const current = ++generation; const today = new Date().toISOString().slice(0, 10); const asOfDate = today.startsWith(selectedMonth) ? today : `${selectedMonth}-28`; const [categories, family, budgets] = await Promise.all([household.listCategories({ includeHidden: true }), household.listFamilyMembers(), household.calculate(selectedMonth, asOfDate)]); if (current !== generation) return; const heading = element("header"); heading.append(element("h2", "Household budgets"), element("p", "Budget consumption follows classified expenses, never transfers, card payments, loan principal, or investment principal.")); const month = input("budgetMonth", "month"); month.value = selectedMonth; month.onchange = () => { selectedMonth = month.value; render(); }; heading.append(field("Review month", month)); const cards = element("div", null, "budget-grid"); for (const item of budgets) { const category = categories.find(({ id }) => id === item.categoryId); const card = element("article", null, `budget-card status-${item.status}`); card.append(element("h3", category?.name ?? "Archived category"), element("strong", `${money.format(item.spentPaise / 100)} of ${money.format(item.availablePaise / 100)}`), element("p", `${money.format(item.remainingPaise / 100)} remaining · ${item.status.replaceAll("-", " ")}`), element("p", item.changeFromPreviousPaise == null ? "No prior-period comparison" : `${money.format(Math.abs(item.changeFromPreviousPaise) / 100)} ${item.changeFromPreviousPaise >= 0 ? "more" : "less"} than last month`)); cards.append(card); } if (!budgets.length) cards.append(element("p", "No budgets saved for this month.")); const categoryList = element("div", null, "category-list"); for (const item of categories) { const row = element("div", null, "recurring-rule"); row.append(element("span", `${item.icon ?? "tag"} · ${item.name} · ${item.classification}${item.hidden ? " · hidden" : ""}`)); const toggle = element("button", item.hidden ? "Show" : "Hide", "button button--secondary"); toggle.onclick = async () => { await household.setCategoryHidden(item.id, !item.hidden); await render(); }; row.append(toggle); categoryList.append(row); } const familyText = family.length ? family.map((item) => `${item.name}${item.relationship ? ` (${item.relationship})` : ""}`).join(", ") : "No family members configured."; const visible = categories.filter(({ hidden }) => !hidden); root.replaceChildren(heading, cards, budgetForm(visible), categoryForm(), subcategoryForm(visible), categoryList, familyForm(), element("p", familyText)); }
  return { element: root, start: render };
}
