const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const element = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };
const paise = (value) => { const match = String(value).trim().match(/^(-?)(\d+)(?:\.(\d{0,2}))?$/); return match ? (match[1] === "-" ? -1 : 1) * (Number(match[2]) * 100 + Number((match[3] ?? "").padEnd(2, "0"))) : NaN; };
const field = (label, control) => { const wrapper = element("label", null, "field"); wrapper.append(element("span", label), control); return wrapper; };
const download = (text) => { const url = URL.createObjectURL(new Blob([text], { type: "application/json" })); const link = element("a"); link.href = url; link.download = `finorbit-integrity-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };

export function createReconciliationCenter({ reconciliation, liveRegion }) {
  const root = element("section", null, "reconciliation-center"); let generation = 0;
  async function act(work, message) { try { await work(); liveRegion.textContent = message; await render(); } catch (error) { liveRegion.textContent = error.message; } }
  function createForm(accounts) {
    const form = element("form", null, "household-form"); const account = element("select"); account.name = "accountId";
    account.append(element("option", "Choose account")); account.firstChild.value = ""; for (const item of accounts) { const option = element("option", item.nickname ?? item.name ?? "Account"); option.value = item.id; account.append(option); }
    const date = element("input"); date.type = "date"; date.name = "statementDate"; date.value = new Date().toISOString().slice(0, 10);
    const balance = element("input"); balance.name = "closingBalance"; balance.inputMode = "decimal"; balance.placeholder = "0.00";
    const submit = element("button", "Start reconciliation", "button"); submit.type = "submit";
    form.append(field("Account", account), field("Statement closing date", date), field("Statement closing balance (₹)", balance), submit);
    form.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(form); const result = await reconciliation.create({ accountId: data.get("accountId"), statementDate: data.get("statementDate"), closingBalancePaise: paise(data.get("closingBalance")) }); if (!result.ok) { liveRegion.textContent = Object.values(result.errors)[0]; return; } liveRegion.textContent = "Reconciliation started."; render(); };
    return form;
  }
  function reconciliationCard(record, data) {
    const account = data.accounts.find((item) => item.id === record.accountId); const card = element("article", null, "reconciliation-card");
    card.append(element("h3", `${account?.nickname ?? account?.name ?? "Account"} · ${record.statementDate}`), element("p", `Statement ${money.format(record.closingBalancePaise / 100)} · FinOrbit ${money.format(record.projectedBalancePaise / 100)}`));
    const difference = element("p", record.differencePaise === 0 ? "Balances match exactly." : `Difference: ${money.format(record.differencePaise / 100)}. Review missing or incorrect transactions, or record an explained correction.`, record.differencePaise === 0 ? "status-success" : "wealth-warning"); card.append(difference);
    if (record.status === "completed") { card.append(element("p", "Completed and locked to its audit trail.")); return card; }
    const eligible = data.transactions.filter((tx) => tx.accountingDate <= record.statementDate && (tx.sourceAccountId === record.accountId || tx.destinationAccountId === record.accountId));
    const form = element("form", null, "reconciliation-transactions"); form.append(element("h4", "Statement transactions"));
    for (const tx of eligible) { const label = element("label"); const checkbox = element("input"); checkbox.type = "checkbox"; checkbox.name = "transactionId"; checkbox.value = tx.id; label.append(checkbox, document.createTextNode(` ${tx.accountingDate} · ${tx.merchantText || tx.type.replaceAll("-", " ")} · ${money.format(tx.amountPaise / 100)} · ${tx.reconciliationState ?? "unreconciled"}`)); form.append(label); }
    if (!eligible.length) form.append(element("p", "No posted transactions are eligible through this statement date."));
    const buttons = element("div", null, "reconciliation-actions"); for (const [state, label] of [["cleared", "Mark cleared"], ["reconciled", "Mark reconciled"]]) { const button = element("button", label, "button button--secondary"); button.type = "button"; button.onclick = () => { const ids = [...form.querySelectorAll("input:checked")].map((item) => item.value); if (!ids.length) { liveRegion.textContent = "Select at least one statement transaction."; return; } act(() => reconciliation.markTransactions(record.id, ids, state), `Selected transactions marked ${state}.`); }; buttons.append(button); }
    if (record.differencePaise !== 0) { const reason = element("input"); reason.placeholder = "Required correction reason"; reason.setAttribute("aria-label", "Correction reason"); const correct = element("button", "Record balance correction", "button button--secondary"); correct.type = "button"; correct.onclick = async () => { const result = await reconciliation.correction(record.id, reason.value); if (!result.ok) { liveRegion.textContent = Object.values(result.errors)[0]; return; } liveRegion.textContent = "Traceable balance correction recorded."; render(); }; buttons.append(reason, correct); }
    const complete = element("button", "Complete reconciliation", "button"); complete.type = "button"; complete.disabled = record.differencePaise !== 0; complete.onclick = () => act(() => reconciliation.complete(record.id), "Reconciliation completed."); buttons.append(complete); form.append(buttons); card.append(form); return card;
  }
  function diagnosticView(diagnostics) {
    const section = element("section", null, "integrity-diagnostics"); const header = element("div", null, "reconciliation-actions"); header.append(element("h2", "Data integrity diagnostics")); const exportButton = element("button", "Export diagnostics", "button button--secondary"); exportButton.onclick = async () => download(await reconciliation.diagnosticJson()); header.append(exportButton); section.append(header, element("p", diagnostics.healthy ? "No blocking integrity errors detected." : "Blocking integrity issues require review."));
    const list = element("ul", null, "diagnostic-list"); for (const issue of diagnostics.issues) { const item = element("li"); item.append(element("strong", issue.code.replaceAll("-", " ")), document.createTextNode(` · ${issue.store} record ${issue.recordId}`)); if (issue.code === "possible-duplicate") item.append(document.createTextNode(` may duplicate ${issue.duplicateId}. Review only; FinOrbit will not delete it automatically.`)); if (issue.code === "broken-reference") item.append(document.createTextNode(` references missing ${issue.targetStore} record ${issue.targetId}.`)); if (issue.code === "orphan-effect") { const repair = element("button", "Archive orphan safely", "button button--secondary"); repair.onclick = () => act(() => reconciliation.archiveOrphanEffect(issue.recordId), "Orphan effect archived; the repair remains reversible."); item.append(repair); } list.append(item); } if (!diagnostics.issues.length) list.append(element("li", "No duplicate, broken-reference, or orphan issues found.")); section.append(list); return section;
  }
  async function render() { const current = ++generation; const [data, diagnostics] = await Promise.all([reconciliation.workspace(), reconciliation.diagnose()]); if (current !== generation) return; const header = element("header"); header.append(element("p", "Match FinOrbit to reality", "route-heading__eyebrow"), element("h2", "Account reconciliation"), element("p", "Enter a statement balance, review transactions, and keep every correction explicit and auditable.")); const list = element("section"); list.append(element("h2", "Reconciliation history")); for (const record of data.reconciliations) list.append(reconciliationCard(record, data)); if (!data.reconciliations.length) list.append(element("p", "No reconciliations yet.")); root.replaceChildren(header, createForm(data.accounts), list, diagnosticView(diagnostics)); }
  return { element: root, start() { root.setAttribute("aria-busy", "true"); return render().finally(() => root.removeAttribute("aria-busy")); } };
}
