import { TRANSACTION_TYPES } from "../../engines/posting-engine.js";
import { runTransaction } from "../../database/transaction.js";

const QUICK = [["expense", "Expense"], ["income", "Income"], ["transfer", "Transfer"], ["credit-card-purchase", "Card purchase"], ["credit-card-payment", "Card payment"], ["loan-payment", "Loan payment"], ["investment-purchase", "Investment purchase"], ["refund", "Refund"]];
const ACCOUNT_SOURCE = new Set(["expense", "transfer", "credit-card-payment", "loan-payment", "investment-purchase", "asset-purchase", "cash-withdrawal", "cash-deposit", "gift-given", "tax-payment"]);
const ACCOUNT_DESTINATION = new Set(["income", "transfer", "loan-disbursement", "investment-sale", "dividend", "interest", "refund", "reimbursement", "asset-sale", "cash-withdrawal", "cash-deposit", "gift-received"]);
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
function paise(value) { const match = String(value).trim().match(/^(\d+)(?:\.(\d{0,2}))?$/); if (!match) return NaN; return Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0")); }
function element(tag, text, className) { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; }

export function createTransactionCenter({ database, transactions, receipts, liveRegion }) {
  const root = element("section", null, "transaction-center"); let entities; let selectedType = "expense"; let editingId = null; let renderGeneration = 0;
  async function loadEntities() { return runTransaction(database, ["accounts", "creditCards", "loans", "investments", "properties", "vehicles", "otherAssets", "categories", "familyMembers"], "readonly", async ({ store }) => ({ accounts: (await store("accounts").getAll()).filter((x) => !x.archived && x.status === "active"), cards: (await store("creditCards").getAll()).filter((x) => !x.archived), loans: (await store("loans").getAll()).filter((x) => !x.archived && x.status !== "closed"), investments: (await store("investments").getAll()).filter((x) => !x.archived), properties: (await store("properties").getAll()).filter((x) => !x.archived && x.status === "active"), vehicles: (await store("vehicles").getAll()).filter((x) => !x.archived && x.status === "active"), otherAssets: (await store("otherAssets").getAll()).filter((x) => !x.archived && x.status === "active"), categories: (await store("categories").getAll()).filter((x) => !x.archived && !x.hidden), familyMembers: (await store("familyMembers").getAll()).filter((x) => !x.archived) })); }
  function selectField(name, label, records) { const wrapper = element("div", null, "field"); const l = element("label", label); const select = document.createElement("select"); select.name = name; select.id = `tx-${name}`; l.htmlFor = select.id; const empty = element("option", "Choose…"); empty.value = ""; select.append(empty, ...records.map((record) => { const option = element("option", record.nickname ?? record.name); option.value = record.id; return option; })); const error = element("p", "", "field__error"); error.id = `${select.id}-error`; wrapper.append(l, select, error); return wrapper; }
  function inputField(name, label, type = "text", value = "") { const wrapper = element("div", null, "field"); const l = element("label", label); const input = document.createElement("input"); input.name = name; input.id = `tx-${name}`; input.type = type; input.value = value; if (name === "amount") input.inputMode = "decimal"; l.htmlFor = input.id; const error = element("p", "", "field__error"); error.id = `${input.id}-error`; wrapper.append(l, input, error); return wrapper; }
  function formView(type = selectedType, existing = {}) {
    selectedType = type; let attachPreviewReceipt = false; const overlay = element("section", null, "transaction-form"); overlay.setAttribute("aria-labelledby", "transaction-form-title"); const title = element("h1", editingId ? "Correct transaction" : "Add transaction"); title.id = "transaction-form-title"; title.tabIndex = -1;
    const form = document.createElement("form"); form.noValidate = true;
    const typeWrap = element("div", null, "field"); const typeLabel = element("label", "Transaction type"); const typeSelect = document.createElement("select"); typeSelect.id = "tx-type"; typeSelect.name = "type"; typeLabel.htmlFor = typeSelect.id; for (const value of TRANSACTION_TYPES) { const option = element("option", value.replaceAll("-", " ")); option.value = value; option.selected = value === type; typeSelect.append(option); } typeSelect.onchange = () => overlay.replaceWith(formView(typeSelect.value)); typeWrap.append(typeLabel, typeSelect);
    form.append(typeWrap, inputField("accountingDate", "Date", "date", existing.accountingDate ?? new Date().toISOString().slice(0, 10)), inputField("amount", "Amount (rupees)", "text", existing.amountPaise == null ? "" : `${Math.floor(existing.amountPaise / 100)}.${String(existing.amountPaise % 100).padStart(2, "0")}`));
    if (ACCOUNT_SOURCE.has(type) || type === "balance-correction") form.append(selectField("sourceAccountId", "Source account", entities.accounts));
    if (ACCOUNT_DESTINATION.has(type)) form.append(selectField("destinationAccountId", "Destination account", entities.accounts));
    if (["credit-card-purchase", "credit-card-payment", "refund"].includes(type)) form.append(selectField("creditCardId", "Credit card", entities.cards));
    if (["loan-disbursement", "loan-payment"].includes(type)) form.append(selectField("loanId", "Loan", entities.loans));
    if (["investment-purchase", "investment-sale"].includes(type)) form.append(selectField("investmentId", "Investment", entities.investments));
    if (["asset-purchase", "asset-sale"].includes(type)) form.append(selectField("propertyId", "Property (choose one asset only)", entities.properties), selectField("vehicleId", "Vehicle (choose one asset only)", entities.vehicles), selectField("otherAssetId", "Other asset (choose one asset only)", entities.otherAssets));
    if (["expense", "income"].includes(type)) form.append(selectField("propertyId", "Related property (optional)", entities.properties), selectField("vehicleId", "Related vehicle (optional)", entities.vehicles), selectField("otherAssetId", "Related other asset (optional)", entities.otherAssets));
    if (["expense", "income", "credit-card-purchase", "loan-payment", "refund", "gift-given", "gift-received", "tax-payment"].includes(type)) form.append(selectField("categoryId", "Category (optional)", entities.categories));
    if (type === "loan-payment") form.append(inputField("principal", "Principal (rupees)"), inputField("interest", "Interest (rupees)"), inputField("fees", "Fees (rupees)"));
    if (["investment-purchase", "investment-sale", "asset-purchase", "asset-sale"].includes(type)) form.append(inputField("fees", "Fees (rupees, optional)"), inputField("taxes", "Taxes (rupees, optional)"));
    if (type === "balance-correction") { form.append(inputField("reason", "Correction reason")); const direction = selectField("direction", "Direction", [{ id: "increase", name: "Increase" }, { id: "decrease", name: "Decrease" }]); form.append(direction); }
    form.append(inputField("merchantText", type === "income" ? "Source" : "Merchant or source (optional)"), inputField("notes", "Notes (optional)"), inputField("tags", "Tags, comma separated (optional)"));
    const receiptField = inputField("receipt", "Receipt image or PDF (optional)", "file"); receiptField.querySelector("input").accept = "image/jpeg,image/png,image/webp,application/pdf"; form.append(receiptField); if (new URLSearchParams(location.search).get("preview") === "1") { const sample = element("button", "Attach synthetic preview receipt", "button button--secondary"); sample.type = "button"; sample.onclick = () => { attachPreviewReceipt = true; sample.disabled = true; sample.textContent = "Synthetic preview receipt attached"; }; form.append(sample); }
    const status = element("p", "", "field__error"); status.setAttribute("role", "alert"); const actions = element("div", null, "transaction-form__actions"); const cancel = element("button", "Cancel", "button button--secondary"); cancel.type = "button"; cancel.onclick = render; const save = element("button", editingId ? "Save correction" : "Quick save", "button"); save.type = "submit"; const another = element("button", "Save and add another", "button button--secondary"); another.type = "button"; actions.append(cancel, another, save); form.append(status, actions);
    async function submit(addAnother) { const data = Object.fromEntries(new FormData(form).entries()); const transaction = { type: data.type, accountingDate: data.accountingDate, amountPaise: paise(data.amount), currency: "INR", sourceAccountId: data.sourceAccountId || undefined, destinationAccountId: data.destinationAccountId || undefined, creditCardId: data.creditCardId || undefined, loanId: data.loanId || undefined, investmentId: data.investmentId || undefined, principalPaise: paise(data.principal || "0"), interestPaise: paise(data.interest || "0"), feesPaise: paise(data.fees || "0"), taxesPaise: paise(data.taxes || "0"), reason: data.reason, direction: data.direction, merchantText: data.merchantText, notes: data.notes, tags: String(data.tags ?? "").split(",").map((v) => v.trim()).filter(Boolean) };
      transaction.categoryId = data.categoryId || undefined; transaction.propertyId = data.propertyId || undefined; transaction.vehicleId = data.vehicleId || undefined; transaction.otherAssetId = data.otherAssetId || undefined; const result = editingId ? await transactions.replace(editingId, transaction) : await transactions.create(transaction); if (!result.ok) { status.textContent = Object.values(result.errors)[0]; const fieldName = Object.keys(result.errors)[0]?.replace("amountPaise", "amount"); form.elements[fieldName]?.focus(); return; }
      const file = form.elements.receipt.files?.[0]; if (file) { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); await receipts.save(result.transaction.id, { name: file.name, type: file.type, size: file.size, contentBase64: btoa(binary) }); } else if (attachPreviewReceipt) { await receipts.save(result.transaction.id, { name: "synthetic-preview-receipt.png", type: "image/png", size: 8, contentBase64: "iVBORw0KGgo=" }); }
      liveRegion.textContent = `Saved ${type.replaceAll("-", " ")} for ${money.format(result.transaction.amountPaise / 100)}.`; editingId = null; if (addAnother) overlay.replaceWith(formView(type)); else render(); }
    form.onsubmit = (event) => { event.preventDefault(); submit(false); }; another.onclick = () => submit(true); overlay.append(title, form); requestAnimationFrame(() => title.focus()); return overlay;
  }
  async function render() {
    const generation = ++renderGeneration; entities ??= await loadEntities(); if (generation !== renderGeneration) return; root.replaceChildren(); const header = element("header", null, "transaction-center__header"); header.append(element("h1", "Transactions"), element("p", "Daily activity from stored postings and opening positions—no invented balances or wealth figures.")); const add = element("button", "Add transaction", "button transaction-center__add"); add.onclick = () => root.replaceChildren(formView()); header.append(add); const quick = element("div", null, "transaction-quick-actions"); for (const [type, label] of QUICK) { const button = element("button", label, "button button--secondary"); button.onclick = () => root.replaceChildren(formView(type)); quick.append(button); }
    const filters = element("form", null, "transaction-filters"); filters.setAttribute("aria-label", "Search and filter transactions"); filters.append(inputField("search", "Search merchant, notes, or tags"), inputField("dateFrom", "From", "date"), inputField("dateTo", "To", "date"), selectField("type", "Type", TRANSACTION_TYPES.map((value) => ({ id: value, name: value.replaceAll("-", " ") }))), selectField("status", "Status", [{ id: "posted", name: "Posted" }, { id: "voided", name: "Voided" }]), selectField("sourceAccountId", "Source account", entities.accounts), selectField("destinationAccountId", "Destination account", entities.accounts), selectField("creditCardId", "Credit card", entities.cards), selectField("loanId", "Loan", entities.loans), selectField("investmentId", "Investment", entities.investments), selectField("categoryId", "Category", entities.categories), selectField("familyMemberId", "Family member", entities.familyMembers), inputField("merchant", "Merchant/source contains"), inputField("tag", "Tag"), inputField("minAmount", "Minimum amount (rupees)"), inputField("maxAmount", "Maximum amount (rupees)"), selectField("receipt", "Receipt", [{ id: "yes", name: "Has receipt" }, { id: "no", name: "No receipt" }])); const apply = element("button", "Apply filters", "button button--secondary"); apply.type = "submit"; filters.append(apply);
    const upcoming = (await runTransaction(database, ["recurringRules"], "readonly", ({ store }) => store("recurringRules").getAll())).filter((r) => r.kind === "commitment" && r.status === "active"); const upcomingBox = element("section", null, "transaction-summary"); upcomingBox.append(element("h2", "Upcoming commitments"), element("p", upcoming.length ? `${upcoming.length} configured template${upcoming.length === 1 ? "" : "s"}; no occurrences have been generated.` : "No active commitment templates."));
    const todayRecords = await transactions.list({ accountingDate: new Date().toISOString().slice(0, 10) }); const todayBox = element("section", null, "transaction-summary"); todayBox.append(element("h2", "Today’s activity"), element("p", todayRecords.length ? `${todayRecords.length} stored transaction${todayRecords.length === 1 ? "" : "s"} today.` : "No transactions recorded today."));
    const warningMessages = []; for (const card of entities.cards) { const outstanding = await transactions.project("creditCard", card.id); if (card.creditLimitPaise != null && outstanding > card.creditLimitPaise) warningMessages.push(`${card.nickname} is above its recorded credit limit.`); } const warningsBox = element("section", null, "transaction-summary"); warningsBox.append(element("h2", "Account and card warnings"), element("p", warningMessages.length ? warningMessages.join(" ") : "No available account or card warnings."));
    const history = element("section", null, "transaction-history"); history.append(element("h2", "Recent transactions")); async function load(filtersValue = {}) { const records = await transactions.list(filtersValue); const list = element("ol", null, "transaction-list"); for (const tx of records) { const item = element("li", null, `transaction-list__item ${tx.status === "voided" ? "is-voided" : ""}`); const summary = element("div"); summary.append(element("strong", tx.merchantText || tx.type.replaceAll("-", " ")), element("span", ` ${tx.accountingDate} · ${money.format(tx.amountPaise / 100)}${tx.receiptIds?.length ? " · Receipt" : ""}${tx.status === "voided" ? " · Voided" : ""}`)); const actions = element("div", null, "transaction-list__actions"); if (tx.status === "posted") { const edit = element("button", "Edit", "button button--secondary"); edit.onclick = () => { editingId = tx.id; root.replaceChildren(formView(tx.type, tx)); }; const duplicate = element("button", "Duplicate", "button button--secondary"); duplicate.onclick = async () => { await transactions.duplicate(tx.id, new Date().toISOString().slice(0, 10)); load(filtersValue); }; const voidButton = element("button", "Void", "button button--secondary"); voidButton.onclick = async () => { const reason = prompt("Why are you voiding this transaction?"); if (reason) { await transactions.void(tx.id, reason); load(filtersValue); } }; actions.append(edit, duplicate, voidButton); } else { const restore = element("button", "Restore", "button button--secondary"); restore.onclick = async () => { if (confirm("Restore this transaction and reapply its effects once?")) { await transactions.restore(tx.id); load(filtersValue); } }; actions.append(restore); } if (tx.receiptIds?.length) { const preview = element("button", "Preview receipt", "button button--secondary"); preview.onclick = async () => { const data = await receipts.preview(tx.receiptIds[0]); const binary = atob(data.contentBase64); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: data.mimeType })); window.open(url, "_blank", "noopener"); setTimeout(() => URL.revokeObjectURL(url), 60000); }; const remove = element("button", "Delete receipt", "button button--secondary"); remove.onclick = async () => { if (confirm("Delete this receipt attachment? The transaction remains.")) { await receipts.remove(tx.receiptIds[0]); load(filtersValue); } }; actions.append(preview, remove); } item.append(summary, actions); list.append(item); } if (!records.length) list.append(element("li", "No matching transactions.")); history.querySelector("ol")?.remove(); history.append(list); }
    filters.onsubmit = (event) => { event.preventDefault(); const data = new FormData(filters); const receipt = data.get("receipt"); load({ search: data.get("search"), dateFrom: data.get("dateFrom"), dateTo: data.get("dateTo"), type: data.get("type"), status: data.get("status"), sourceAccountId: data.get("sourceAccountId"), destinationAccountId: data.get("destinationAccountId"), creditCardId: data.get("creditCardId"), loanId: data.get("loanId"), investmentId: data.get("investmentId"), categoryId: data.get("categoryId"), familyMemberId: data.get("familyMemberId"), merchant: data.get("merchant"), tag: data.get("tag"), minAmountPaise: data.get("minAmount") ? paise(data.get("minAmount")) : undefined, maxAmountPaise: data.get("maxAmount") ? paise(data.get("maxAmount")) : undefined, hasReceipt: receipt === "yes" ? true : receipt === "no" ? false : undefined }); }; if (generation !== renderGeneration) return; root.append(header, quick, todayBox, upcomingBox, warningsBox, filters, history); load();
  }
  return { element: root, start() { root.setAttribute("aria-busy", "true"); return render().finally(() => root.removeAttribute("aria-busy")); } };
}
