const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const element = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };
const field = (label, control) => { const wrapper = element("label", null, "field"); wrapper.append(element("span", label), control); return wrapper; };
const input = (name, type = "text", value = "") => { const node = element("input"); node.name = name; node.type = type; node.value = value; return node; };
const toPaise = (value) => { const match = String(value).trim().match(/^(\d+)(?:\.(\d{1,2}))?$/); return match ? Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0")) : null; };

export function createPortfolioCenter({ portfolio, marketData, liveRegion }) {
  const root = element("section", null, "portfolio-center"); let generation = 0;
  function lotForm(investments) { const form = element("form", null, "wealth-tool-form"); const investment = element("select"); investment.name = "investmentId"; investment.append(new Option("Choose investment", ""), ...investments.map((item) => new Option(item.name, item.id))); const submit = element("button", "Add investment lot", "button"); submit.type = "submit"; form.append(field("Investment", investment), field("Purchase date", input("purchaseDate", "date", new Date().toISOString().slice(0, 10))), field("Quantity or units", input("quantity")), field("Cost basis (rupees)", input("costBasis")), submit); form.onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const costBasisPaise = toPaise(data.costBasis); const result = await portfolio.saveLot({ investmentId: data.investmentId, purchaseDate: data.purchaseDate, quantity: data.quantity, costBasisPaise }); liveRegion.textContent = result.ok ? "Investment lot added without changing current market price." : Object.values(result.errors)[0]; if (result.ok) await render(); }; return form; }
  async function render() { const current = ++generation; const [summary, investments] = await Promise.all([portfolio.calculate(), portfolio.listInvestments()]); if (current !== generation) return; const heading = element("header", null, "wealth-center__header"); heading.append(element("h2", "Investment portfolio"), element("p", "Cost basis and holdings remain independent from cached or provider prices.")); const refresh = element("button", navigator.onLine ? "Refresh configured prices" : "Offline · using cached prices", "button button--secondary"); refresh.disabled = !navigator.onLine; refresh.onclick = async () => { refresh.disabled = true; const results = await marketData.refresh(investments); const updated = results.filter(({ status }) => status === "updated").length; liveRegion.textContent = updated ? `${updated} price${updated === 1 ? "" : "s"} refreshed.` : "No prices changed; cached and manual values remain intact."; await render(); }; heading.append(refresh); const totals = element("div", null, "wealth-summary"); for (const [label, amount] of [["Cost basis", summary.costBasisPaise], ["Current value", summary.currentValuePaise], ["Unrealised gain", summary.unrealisedGainPaise], ["Realised gain", summary.realisedGainPaise]]) { const card = element("article", null, "wealth-card"); card.append(element("p", label), element("strong", money.format(amount / 100))); totals.append(card); } const list = element("div", null, "portfolio-list"); for (const item of summary.holdings) { const row = element("article", null, "wealth-history"); row.append(element("h3", item.name), element("p", `${item.assetClass ?? "custom"} · ${item.quantity} units`), element("p", `${money.format(item.currentValuePaise / 100)} current · ${money.format(item.costBasisPaise / 100)} cost`), element("p", `Price: ${item.priceSource}${item.manualOverride ? " override" : ""}${item.priceTimestamp ? ` · ${item.priceTimestamp}` : " · no live timestamp"}`)); list.append(row); } if (!summary.holdings.length) list.append(element("p", "No active investments configured.")); const tools = element("section", null, "wealth-tools"); tools.append(element("h3", "Record a purchase lot"), lotForm(investments)); root.replaceChildren(heading, totals, list, tools); }
  return { element: root, start: render };
}
